version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data_volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${DB_PASS}

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data_volume:/var/www/html
      - ./src:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASS}
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data_volume: {}
  wordpress_data_volume: {}